import { StyleSheet } from 'react-native';
import COLORS from '@/assets/colors';
import TYPOGRAPHY from '@/assets/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 20,
  },
  title: {
    fontSize: TYPOGRAPHY.size.xxxl,
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: 30,
    fontWeight: TYPOGRAPHY.weights.bold,
  },
  formContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: TYPOGRAPHY.size.md,
    color: COLORS.white,
    marginBottom: 8,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  input: {
    backgroundColor: COLORS.lightBackground,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  ratingButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.lightBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  ratingButtonActive: {
    backgroundColor: COLORS.brandPrimary,
    borderColor: COLORS.brandPrimary,
  },
  ratingText: {
    fontSize: 16,
    color: COLORS.white,
  },
  initializingText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  submitButton: {
    backgroundColor: COLORS.brandPrimary,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  microphoneSection: {
    alignItems: 'center',
    marginTop: 20,
  },
  micButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.brandPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  micButtonRecording: {
    backgroundColor: COLORS.errorRed,
  },
  micIcon: {
    fontSize: 32,
    color: COLORS.white,
  },
  decibelDisplay: {
    alignItems: 'center',
    marginBottom: 20,
  },
  decibelValue: {
    fontSize: TYPOGRAPHY.size.xxxl,
    color: COLORS.brandPrimary,
    fontWeight: TYPOGRAPHY.weights.bold,
    marginBottom: 8,
  },
  decibelLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  soundLevelBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 60,
    marginBottom: 16,
  },
  soundBar: {
    width: 8,
    backgroundColor: COLORS.brandPrimary,
    marginHorizontal: 2,
    borderRadius: 4,
  },
  sensitivityIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sensitivityDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginHorizontal: 4,
  },
  sensitivityDotActive: {
    backgroundColor: COLORS.brandPrimary,
  },
  sensitivityDotInactive: {
    backgroundColor: COLORS.borderDarkColor,
  },
  recordingIndicator: {
    alignItems: 'center',
    marginTop: 16,
  },
  recordingPulse: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.errorRed,
    marginBottom: 8,
  },
  recordingIndicatorText: {
    fontSize: TYPOGRAPHY.size.md,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    marginBottom: 4,
  },
  recordingCounterText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  statusText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
  },
  // Additional styles for the component
  scrollContainer: {
    flexGrow: 1,
    padding: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 20,
  },
  subtitle: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.regular,
    color: COLORS.textLight,
    textAlign: 'center',
  },
  walletStatus: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
    alignSelf: 'center',
  },
  walletStatusText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  micContainer: {
    alignItems: 'center',
    marginBottom: 30,
    padding: 20,
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  micLabel: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
    marginBottom: 20,
  },
  micButtonInner: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  recordingStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.errorRed,
    marginRight: 8,
  },
  recordingText: {
    color: COLORS.errorRed,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  dbDisplay: {
    alignItems: 'center',
    marginTop: 20,
    padding: 16,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  dbLabel: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginBottom: 8,
  },
  dbValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  dbValue: {
    fontSize: TYPOGRAPHY.size.xxxl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.brandPrimary,
  },
  dbUnit: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginLeft: 8,
  },
  dbStatus: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginTop: 4,
    textAlign: 'center',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.brandGreen,
    marginRight: 6,
  },
  liveText: {
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.brandGreen,
    letterSpacing: 1,
  },
  timestampContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timestampInput: {
    flex: 1,
    marginRight: 12,
  },
  timestampButton: {
    backgroundColor: COLORS.brandPrimary,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timestampButtonText: {
    color: COLORS.white,
    fontWeight: '600',
    fontSize: 14,
  },
  infoContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  infoTitle: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
    marginBottom: 12,
  },
  infoText: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.regular,
    color: COLORS.textLight,
    lineHeight: 22,
  },
  audioLevelBar: {
    width: '100%',
    height: 20,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 10,
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  audioLevelBarBackground: {
    flex: 1,
    backgroundColor: COLORS.borderDarkColor,
    borderRadius: 10,
    overflow: 'hidden',
  },
  audioLevelBarFill: {
    height: '100%',
    borderRadius: 10,
  },
  audioLevelText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 5,
  },
}); 