import { StyleSheet } from 'react-native';
import COLORS from '@/assets/colors';
import TYPOGRAPHY from '@/assets/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 20,
  },
  title: {
    fontSize: TYPOGRAPHY.size.xxxl,
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: 30,
    fontWeight: TYPOGRAPHY.weights.bold,
  },
  formContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: TYPOGRAPHY.size.md,
    color: COLORS.white,
    marginBottom: 8,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  input: {
    backgroundColor: COLORS.lightBackground,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  ratingButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.lightBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  ratingButtonActive: {
    backgroundColor: COLORS.brandPrimary,
    borderColor: COLORS.brandPrimary,
  },
  ratingText: {
    fontSize: 16,
    color: COLORS.white,
  },
  initializingText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  submitButton: {
    backgroundColor: COLORS.brandPrimary,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  microphoneSection: {
    alignItems: 'center',
    marginTop: 20,
  },
  micButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.brandPrimary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  micButtonRecording: {
    backgroundColor: COLORS.errorRed,
  },
  micIcon: {
    fontSize: 32,
    color: COLORS.white,
  },
  decibelDisplay: {
    alignItems: 'center',
    marginBottom: 20,
  },
  decibelValue: {
    fontSize: TYPOGRAPHY.size.xxxl,
    color: COLORS.brandPrimary,
    fontWeight: TYPOGRAPHY.weights.bold,
    marginBottom: 8,
  },
  decibelLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  soundLevelBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 60,
    marginBottom: 16,
  },
  soundBar: {
    width: 8,
    backgroundColor: COLORS.brandPrimary,
    marginHorizontal: 2,
    borderRadius: 4,
  },
  sensitivityIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sensitivityDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginHorizontal: 4,
  },
  sensitivityDotActive: {
    backgroundColor: COLORS.brandPrimary,
  },
  sensitivityDotInactive: {
    backgroundColor: COLORS.borderDarkColor,
  },
  recordingIndicator: {
    alignItems: 'center',
    marginTop: 16,
  },
  recordingPulse: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.errorRed,
    marginBottom: 8,
  },
  recordingIndicatorText: {
    fontSize: TYPOGRAPHY.size.md,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    marginBottom: 4,
  },
  recordingCounterText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  statusText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
  },
  // Additional styles for the component
  scrollContainer: {
    flexGrow: 1,
    padding: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
    marginTop: 20,
  },
  subtitle: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.regular,
    color: COLORS.textLight,
    textAlign: 'center',
  },
  walletStatus: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
    alignSelf: 'center',
  },
  walletStatusText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  micContainer: {
    alignItems: 'center',
    marginBottom: 30,
    padding: 20,
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  micLabel: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
    marginBottom: 20,
  },
  micButtonInner: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  recordingStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.errorRed,
    marginRight: 8,
  },
  recordingText: {
    color: COLORS.errorRed,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  dbDisplay: {
    alignItems: 'center',
    marginTop: 20,
    padding: 16,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  dbLabel: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginBottom: 8,
  },
  dbValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  dbValue: {
    fontSize: TYPOGRAPHY.size.xxxl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.brandPrimary,
  },
  dbUnit: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginLeft: 8,
  },
  dbStatus: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    marginTop: 4,
    textAlign: 'center',
  },
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.brandGreen,
    marginRight: 6,
  },
  liveText: {
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.brandGreen,
    letterSpacing: 1,
  },
  timestampContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timestampInput: {
    flex: 1,
    marginRight: 12,
  },
  timestampButton: {
    backgroundColor: COLORS.brandPrimary,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timestampButtonText: {
    color: COLORS.white,
    fontWeight: '600',
    fontSize: 14,
  },
  infoContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  infoTitle: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
    marginBottom: 12,
  },
  infoText: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.regular,
    color: COLORS.textLight,
    lineHeight: 22,
  },
  audioLevelBar: {
    width: '100%',
    height: 20,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 10,
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  audioLevelBarBackground: {
    flex: 1,
    backgroundColor: COLORS.borderDarkColor,
    borderRadius: 10,
    overflow: 'hidden',
  },
  audioLevelBarFill: {
    height: '100%',
    borderRadius: 10,
  },
  audioLevelText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 5,
  },
  // Wallet connection styles
  walletConnectedContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.brandGreen,
  },
  walletStatusConnected: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  walletProviderText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  walletAddressText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    fontFamily: 'monospace',
    marginBottom: 12,
    textAlign: 'center',
  },
  disconnectButton: {
    backgroundColor: COLORS.errorRed,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'center',
  },
  disconnectButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    textAlign: 'center',
  },
  walletDisconnectedContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  walletStatusDisconnected: {
    marginBottom: 16,
  },
  walletSubtext: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 4,
  },
  connectionOptionsContainer: {
    gap: 12,
  },
  connectButton: {
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  googleButton: {
    backgroundColor: '#4285F4',
  },
  appleButton: {
    backgroundColor: '#000000',
  },
  emailButton: {
    backgroundColor: COLORS.brandPrimary,
  },
  dynamicButton: {
    backgroundColor: '#6366F1',
  },
  turnkeyButton: {
    backgroundColor: '#10B981',
  },
  mwaButton: {
    backgroundColor: '#8B5CF6', // Purple color for MWA
  },
  connectButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  mwaInfoText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 18,
  },
  noProviderText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  connectingIndicator: {
    marginTop: 16,
    alignItems: 'center',
  },
  connectingText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    fontStyle: 'italic',
  },
  connectWalletPrompt: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 24,
    marginTop: 24,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  connectWalletPromptText: {
    fontSize: TYPOGRAPHY.size.lg,
    color: COLORS.textDarkColor,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    textAlign: 'center',
    marginBottom: 8,
  },
  connectWalletPromptSubtext: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
    lineHeight: 20,
  },
  
  // Wallet balance styles
  walletBalanceContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 16,
    marginTop: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  balanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  balanceTitle: {
    fontSize: TYPOGRAPHY.size.md,
    color: COLORS.textDarkColor,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  refreshButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.brandPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  refreshButtonText: {
    fontSize: 16,
    color: COLORS.white,
  },
  balanceDetails: {
    gap: 12,
  },
  balanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  balanceLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  balanceValue: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textDarkColor,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    fontFamily: 'monospace',
  },
  balanceValueContainer: {
    minWidth: 80,
    alignItems: 'flex-end',
  },
  balanceLoading: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    fontStyle: 'italic',
  },
  balanceError: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.errorRed,
    fontStyle: 'italic',
  },
  networkInfo: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderDarkColor,
    alignItems: 'center',
  },
  networkText: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
    fontStyle: 'italic',
  },
  createUserButton: {
    backgroundColor: COLORS.brandPrimary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  createUserButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
}); 